import { useState, useEffect } from "react";
import SideBarMenu from "../components/SideBarMenu";
import Header from "../components/Header";
import { useAuth } from "../context/AuthContext";
import Modal from "../components/common/Modal";
import type { ModalType } from "../components/common/Modal";

interface SettingsSection {
  id: string;
  title: string;
  description: string;
  icon: string;
}

const SettingsScreen = () => {
  const { user, updateProfile } = useAuth();
  const [activeSection, setActiveSection] = useState("general");
  const [settings, setSettings] = useState({
    // Configurações Gerais - serão carregadas do usuário
    storeName: "",
    storeDescription: "",
    storeEmail: "",
    storePhone: "",
    storeAddress: "",
    timezone: "America/Sao_Paulo",
    currency: "BRL",
    language: "pt-BR",

    // Configurações de Produtos
    autoGenerateDescriptions: true,
    autoCompressImages: true,
    maxImageSize: 2, // MB
    imageQuality: 85,
    defaultCategory: "Geral",
    requireProductImages: true,

    // Configurações de Importação
    importDateFormat: "DD/MM/YYYY",
    importDecimalSeparator: ",",
    importThousandSeparator: ".",
    autoCreateCategories: true,
    skipEmptyRows: true,

    // Configurações de Exportação
    exportDateFormat: "DD/MM/YYYY",
    exportDecimalSeparator: ",",
    exportThousandSeparator: ".",
    includeProductImages: true,
    compressExportedImages: true,

    // Configurações de Notificações
    emailNotifications: true,
    productAlerts: true,
    importAlerts: true,
    exportAlerts: true,
    weeklyReports: false,

    // Configurações de Segurança
    twoFactorAuth: false,
    sessionTimeout: 30, // minutos
    passwordExpiry: 90, // dias
    loginAttempts: 5,

    // Configurações de Integração
    shopifyApiKey: "",
    amazonApiKey: "",
    mercadoLivreApiKey: "",
    autoSync: false,
    syncInterval: 60, // minutos
  });

  // Modal State
  const [modalConfig, setModalConfig] = useState<{
    isOpen: boolean;
    type: ModalType;
    title: string;
    message: string;
    onConfirm?: () => void;
  }>({
    isOpen: false,
    type: "alert",
    title: "",
    message: "",
  });

  const closeModal = () => {
    setModalConfig((prev) => ({ ...prev, isOpen: false }));
  };

  const showModal = (type: ModalType, title: string, message: string) => {
    setModalConfig({
      isOpen: true,
      type,
      title,
      message,
    });
  };

  // Carregar configurações do usuário quando o componente montar
  useEffect(() => {
    if (user?.settings && Object.keys(user.settings).length > 0) {
      setSettings((prev) => ({
        ...prev,
        ...user.settings,
      }));
    }
  }, [user]);

  const sections: SettingsSection[] = [
    {
      id: "general",
      title: "Geral",
      description: "Informações básicas da loja",
      icon: "fa-solid fa-store",
    },
    {
      id: "products",
      title: "Produtos",
      description: "Configurações de produtos",
      icon: "fa-solid fa-box",
    },
    {
      id: "import",
      title: "Importação",
      description: "Configurações de importação",
      icon: "fa-solid fa-file-import",
    },
    {
      id: "export",
      title: "Exportação",
      description: "Configurações de exportação",
      icon: "fa-solid fa-file-export",
    },
    {
      id: "notifications",
      title: "Notificações",
      description: "Configurações de alertas",
      icon: "fa-solid fa-bell",
    },
    {
      id: "security",
      title: "Segurança",
      description: "Configurações de segurança",
      icon: "fa-solid fa-shield-halved",
    },
    {
      id: "integrations",
      title: "Integrações",
      description: "APIs e marketplaces",
      icon: "fa-solid fa-plug",
    },
  ];

  const handleSettingChange = (key: string, value: any) => {
    setSettings((prev) => ({
      ...prev,
      [key]: value,
    }));
  };

  const handleSaveSettings = async () => {
    try {
      // Salvar configurações no backend através do perfil do usuário
      await updateProfile({
        settings: settings,
      });
      showModal("success", "Sucesso", "Configurações salvas com sucesso!");
    } catch (error) {
      console.error("Erro ao salvar configurações:", error);
      showModal(
        "error",
        "Erro",
        "Erro ao salvar configurações. Tente novamente."
      );
    }
  };

  const renderGeneralSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Informações da Loja</h3>
        <div className="form-group">
          <label>Nome da Loja</label>
          <input
            type="text"
            value={settings.storeName}
            onChange={(e) => handleSettingChange("storeName", e.target.value)}
            placeholder="Digite o nome da sua loja"
          />
        </div>
        <div className="form-group">
          <label>Descrição</label>
          <textarea
            value={settings.storeDescription}
            onChange={(e) =>
              handleSettingChange("storeDescription", e.target.value)
            }
            placeholder="Descreva sua loja"
            rows={3}
          />
        </div>
        <div className="form-row">
          <div className="form-group">
            <label>E-mail</label>
            <input
              type="email"
              value={settings.storeEmail}
              onChange={(e) =>
                handleSettingChange("storeEmail", e.target.value)
              }
              placeholder="contato@minhaloja.com"
            />
          </div>
          <div className="form-group">
            <label>Telefone</label>
            <input
              type="tel"
              value={settings.storePhone}
              onChange={(e) =>
                handleSettingChange("storePhone", e.target.value)
              }
              placeholder="(11) 99999-9999"
            />
          </div>
        </div>
        <div className="form-group">
          <label>Endereço</label>
          <input
            type="text"
            value={settings.storeAddress}
            onChange={(e) =>
              handleSettingChange("storeAddress", e.target.value)
            }
            placeholder="Endereço completo da loja"
          />
        </div>
      </div>

      <div className="settings-group">
        <h3>Localização</h3>
        <div className="form-row">
          <div className="form-group">
            <label>Fuso Horário</label>
            <select
              value={settings.timezone}
              onChange={(e) => handleSettingChange("timezone", e.target.value)}
            >
              <option value="America/Sao_Paulo">São Paulo (GMT-3)</option>
              <option value="America/New_York">Nova York (GMT-5)</option>
              <option value="Europe/London">Londres (GMT+0)</option>
            </select>
          </div>
          <div className="form-group">
            <label>Moeda</label>
            <select
              value={settings.currency}
              onChange={(e) => handleSettingChange("currency", e.target.value)}
            >
              <option value="BRL">Real (R$)</option>
              <option value="USD">Dólar ($)</option>
              <option value="EUR">Euro (€)</option>
            </select>
          </div>
        </div>
        <div className="form-group">
          <label>Idioma</label>
          <select
            value={settings.language}
            onChange={(e) => handleSettingChange("language", e.target.value)}
          >
            <option value="pt-BR">Português (Brasil)</option>
            <option value="en-US">English (US)</option>
            <option value="es-ES">Español</option>
          </select>
        </div>
      </div>
    </div>
  );

  const renderProductSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Automação de Produtos</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.autoGenerateDescriptions}
              onChange={(e) =>
                handleSettingChange(
                  "autoGenerateDescriptions",
                  e.target.checked
                )
              }
            />
            <span className="checkmark"></span>
            Gerar descrições automaticamente com IA
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.autoCompressImages}
              onChange={(e) =>
                handleSettingChange("autoCompressImages", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Comprimir imagens automaticamente
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.requireProductImages}
              onChange={(e) =>
                handleSettingChange("requireProductImages", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Exigir imagem para todos os produtos
          </label>
        </div>
      </div>

      <div className="settings-group">
        <h3>Configurações de Imagem</h3>
        <div className="form-row">
          <div className="form-group">
            <label>Tamanho máximo (MB)</label>
            <input
              type="number"
              value={settings.maxImageSize}
              onChange={(e) =>
                handleSettingChange("maxImageSize", parseInt(e.target.value))
              }
              min="1"
              max="10"
            />
          </div>
          <div className="form-group">
            <label>Qualidade (%)</label>
            <input
              type="number"
              value={settings.imageQuality}
              onChange={(e) =>
                handleSettingChange("imageQuality", parseInt(e.target.value))
              }
              min="50"
              max="100"
            />
          </div>
        </div>
      </div>

      <div className="settings-group">
        <h3>Categorias</h3>
        <div className="form-group">
          <label>Categoria padrão</label>
          <input
            type="text"
            value={settings.defaultCategory}
            onChange={(e) =>
              handleSettingChange("defaultCategory", e.target.value)
            }
            placeholder="Categoria padrão para novos produtos"
          />
        </div>
      </div>
    </div>
  );

  const renderImportSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Formato de Dados</h3>
        <div className="form-row">
          <div className="form-group">
            <label>Formato de Data</label>
            <select
              value={settings.importDateFormat}
              onChange={(e) =>
                handleSettingChange("importDateFormat", e.target.value)
              }
            >
              <option value="DD/MM/YYYY">DD/MM/YYYY</option>
              <option value="MM/DD/YYYY">MM/DD/YYYY</option>
              <option value="YYYY-MM-DD">YYYY-MM-DD</option>
            </select>
          </div>
          <div className="form-group">
            <label>Separador Decimal</label>
            <select
              value={settings.importDecimalSeparator}
              onChange={(e) =>
                handleSettingChange("importDecimalSeparator", e.target.value)
              }
            >
              <option value=",">Vírgula (,)</option>
              <option value=".">Ponto (.)</option>
            </select>
          </div>
        </div>
        <div className="form-group">
          <label>Separador de Milhares</label>
          <select
            value={settings.importThousandSeparator}
            onChange={(e) =>
              handleSettingChange("importThousandSeparator", e.target.value)
            }
          >
            <option value=".">Ponto (.)</option>
            <option value=",">Vírgula (,)</option>
            <option value=" ">Espaço ( )</option>
          </select>
        </div>
      </div>

      <div className="settings-group">
        <h3>Comportamento da Importação</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.autoCreateCategories}
              onChange={(e) =>
                handleSettingChange("autoCreateCategories", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Criar categorias automaticamente
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.skipEmptyRows}
              onChange={(e) =>
                handleSettingChange("skipEmptyRows", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Pular linhas vazias
          </label>
        </div>
      </div>
    </div>
  );

  const renderExportSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Formato de Exportação</h3>
        <div className="form-row">
          <div className="form-group">
            <label>Formato de Data</label>
            <select
              value={settings.exportDateFormat}
              onChange={(e) =>
                handleSettingChange("exportDateFormat", e.target.value)
              }
            >
              <option value="DD/MM/YYYY">DD/MM/YYYY</option>
              <option value="MM/DD/YYYY">MM/DD/YYYY</option>
              <option value="YYYY-MM-DD">YYYY-MM-DD</option>
            </select>
          </div>
          <div className="form-group">
            <label>Separador Decimal</label>
            <select
              value={settings.exportDecimalSeparator}
              onChange={(e) =>
                handleSettingChange("exportDecimalSeparator", e.target.value)
              }
            >
              <option value=",">Vírgula (,)</option>
              <option value=".">Ponto (.)</option>
            </select>
          </div>
        </div>
      </div>

      <div className="settings-group">
        <h3>Conteúdo da Exportação</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.includeProductImages}
              onChange={(e) =>
                handleSettingChange("includeProductImages", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Incluir imagens dos produtos
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.compressExportedImages}
              onChange={(e) =>
                handleSettingChange("compressExportedImages", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Comprimir imagens na exportação
          </label>
        </div>
      </div>
    </div>
  );

  const renderNotificationSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Notificações por E-mail</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.emailNotifications}
              onChange={(e) =>
                handleSettingChange("emailNotifications", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Ativar notificações por e-mail
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.productAlerts}
              onChange={(e) =>
                handleSettingChange("productAlerts", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Alertas de produtos
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.importAlerts}
              onChange={(e) =>
                handleSettingChange("importAlerts", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Alertas de importação
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.exportAlerts}
              onChange={(e) =>
                handleSettingChange("exportAlerts", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Alertas de exportação
          </label>
        </div>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.weeklyReports}
              onChange={(e) =>
                handleSettingChange("weeklyReports", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Relatórios semanais
          </label>
        </div>
      </div>
    </div>
  );

  const renderSecuritySettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>Autenticação</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.twoFactorAuth}
              onChange={(e) =>
                handleSettingChange("twoFactorAuth", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Autenticação de dois fatores
          </label>
        </div>
        <div className="form-row">
          <div className="form-group">
            <label>Timeout da Sessão (minutos)</label>
            <input
              type="number"
              value={settings.sessionTimeout}
              onChange={(e) =>
                handleSettingChange("sessionTimeout", parseInt(e.target.value))
              }
              min="5"
              max="480"
            />
          </div>
          <div className="form-group">
            <label>Expiração da Senha (dias)</label>
            <input
              type="number"
              value={settings.passwordExpiry}
              onChange={(e) =>
                handleSettingChange("passwordExpiry", parseInt(e.target.value))
              }
              min="30"
              max="365"
            />
          </div>
        </div>
        <div className="form-group">
          <label>Tentativas de Login</label>
          <input
            type="number"
            value={settings.loginAttempts}
            onChange={(e) =>
              handleSettingChange("loginAttempts", parseInt(e.target.value))
            }
            min="3"
            max="10"
          />
        </div>
      </div>
    </div>
  );

  const renderIntegrationSettings = () => (
    <div className="settings-content">
      <div className="settings-group">
        <h3>APIs de Marketplaces</h3>
        <div className="form-group">
          <label>Shopify API Key</label>
          <input
            type="password"
            value={settings.shopifyApiKey}
            onChange={(e) =>
              handleSettingChange("shopifyApiKey", e.target.value)
            }
            placeholder="Digite sua API key do Shopify"
          />
        </div>
        <div className="form-group">
          <label>Amazon API Key</label>
          <input
            type="password"
            value={settings.amazonApiKey}
            onChange={(e) =>
              handleSettingChange("amazonApiKey", e.target.value)
            }
            placeholder="Digite sua API key do Amazon"
          />
        </div>
        <div className="form-group">
          <label>Mercado Livre API Key</label>
          <input
            type="password"
            value={settings.mercadoLivreApiKey}
            onChange={(e) =>
              handleSettingChange("mercadoLivreApiKey", e.target.value)
            }
            placeholder="Digite sua API key do Mercado Livre"
          />
        </div>
      </div>

      <div className="settings-group">
        <h3>Sincronização Automática</h3>
        <div className="form-group">
          <label className="checkbox-label">
            <input
              type="checkbox"
              checked={settings.autoSync}
              onChange={(e) =>
                handleSettingChange("autoSync", e.target.checked)
              }
            />
            <span className="checkmark"></span>
            Ativar sincronização automática
          </label>
        </div>
        <div className="form-group">
          <label>Intervalo de Sincronização (minutos)</label>
          <input
            type="number"
            value={settings.syncInterval}
            onChange={(e) =>
              handleSettingChange("syncInterval", parseInt(e.target.value))
            }
            min="15"
            max="1440"
            disabled={!settings.autoSync}
          />
        </div>
      </div>
    </div>
  );

  const renderActiveSection = () => {
    switch (activeSection) {
      case "general":
        return renderGeneralSettings();
      case "products":
        return renderProductSettings();
      case "import":
        return renderImportSettings();
      case "export":
        return renderExportSettings();
      case "notifications":
        return renderNotificationSettings();
      case "security":
        return renderSecuritySettings();
      case "integrations":
        return renderIntegrationSettings();
      default:
        return renderGeneralSettings();
    }
  };

  return (
    <div>
      <Header />
      <SideBarMenu pageName="settings" />

      <main className="app-main">
        <div className="settings-container">
          <div className="settings-header">
            <div className="page-title">
              <h1>Configurações</h1>
              <p>Gerencie as configurações da sua plataforma</p>
            </div>
            <button className="save-btn" onClick={handleSaveSettings}>
              <i className="fa-solid fa-save"></i>
              Salvar Configurações
            </button>
          </div>

          <div className="settings-layout">
            <div className="settings-sidebar">
              <div className="settings-nav">
                {sections.map((section) => (
                  <button
                    key={section.id}
                    className={`settings-nav-item ${
                      activeSection === section.id ? "active" : ""
                    }`}
                    onClick={() => setActiveSection(section.id)}
                  >
                    <div className="nav-icon">
                      <i className={section.icon}></i>
                    </div>
                    <div className="nav-content">
                      <span className="nav-title">{section.title}</span>
                      <span className="nav-description">
                        {section.description}
                      </span>
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <div className="settings-main">
              <div className="settings-section">
                <div className="section-header">
                  <h2>{sections.find((s) => s.id === activeSection)?.title}</h2>
                  <p>
                    {sections.find((s) => s.id === activeSection)?.description}
                  </p>
                </div>
                {renderActiveSection()}
              </div>
            </div>
          </div>
        </div>
      </main>

      <Modal
        isOpen={modalConfig.isOpen}
        onClose={closeModal}
        type={modalConfig.type}
        title={modalConfig.title}
        message={modalConfig.message}
        onConfirm={closeModal}
      />
    </div>
  );
};

export default SettingsScreen;
